const FAQS = [
    {
        q: "Is this really free?",
        a: "Yes. Every tutorial is free on YouTube and every practice PDF is free to download. No paywall, no email gate, no upsell.",
    },
    {
        q: "How is this different from Khan Academy SAT prep?",
        a: "This channel is built for the Digital SAT (post-March 2024) and ships two long-form tutorials a week plus a YouTube Short most days. Each lesson teaches 3 named rules first, then walks 8 examples easy-to-hard — and every wrong answer is explained, not just the right one.",
    },
    {
        q: "What does ‘AI-validated explanations’ mean?",
        a: "Every per-choice explanation is generated by Claude Opus and re-checked by a separate logic critic. Anything ambiguous or wrong is flagged and regenerated. No voiceover or video is rendered until every explanation passes the gate.",
    },
    {
        q: "How is the Digital SAT Reading & Writing scored?",
        a: "Reading & Writing is scored from 200 to 800. The section is adaptive: your performance on Module 1 determines whether Module 2 is easier or harder, and the difficulty of Module 2 affects your scoring band. Roughly 54 questions decide the entire R&W score.",
    },
    {
        q: "What topics are tested on Digital SAT Reading & Writing?",
        a: "There are 10 question types across four content domains: Information & Ideas (central ideas, command of evidence, inferences), Craft & Structure (words in context, text structure & purpose, cross-text connections), Expression of Ideas (rhetorical synthesis, transitions), and Standard English Conventions (boundaries, form/structure/sense). The channel covers every one of them.",
    },
    {
        q: "How long is the Digital SAT Reading & Writing section?",
        a: "Two modules of 32 minutes each — 64 minutes total. Each module has 27 questions (25 scored + 2 experimental). That's roughly 71 seconds per question, which is why pattern recognition matters more than slow re-reading.",
    },
    {
        q: "Is Khan Academy SAT prep enough for the Digital SAT?",
        a: "Khan Academy is a solid foundation and the official partner of College Board, but it leans heavily on legacy paper-test material with Bluebook practice tests layered on top. If you want focused drill on the Digital SAT format with every wrong answer explained per-choice, supplement Khan with this channel — they cover different gaps.",
    },
    {
        q: "When should I start prepping for the Digital SAT?",
        a: "Most students benefit from 2–3 months of consistent prep — about 4–6 hours per week. If you're starting earlier, drop the daily Shorts into your feed and watch one long-form tutorial per weekend. If you're cramming in a month, do one tutorial a day and one full Bluebook practice test per week.",
    },
    {
        q: "Do you cover Math too?",
        a: "Right now the channel focuses exclusively on Reading & Writing — all 10 SAT R&W question types are in active rotation. Math is on the roadmap.",
    },
    {
        q: "Are the practice tests scored like the real Digital SAT?",
        a: "Practice tests are 54 questions per module, matching the real Digital SAT module length. Difficulty is calibrated 30% easy / 40% medium / 30% hard, and a downloadable PDF ships with every tutorial.",
    },
    {
        q: "Are these tutorials helpful for the PSAT too?",
        a: "Yes. The PSAT/NMSQT uses the same Digital SAT R&W question types and the same adaptive format — just slightly easier difficulty calibration. Every rule and trap covered here transfers directly.",
    },
    {
        q: "Do I need to download the practice PDFs to follow along?",
        a: "No. Each video is fully self-contained — passages, choices, and explanations all appear on screen. The PDFs are bonus material for students who want to retake the practice problems on paper or quiz themselves later.",
    },
];

export function FAQ() {
    return (
        <section className="section">
            <div className="container container-prose">
                <div className="section-eyebrow">FAQ</div>
                <h2>Frequently Asked Questions</h2>
                <p className="section-lede">
                    Everything students and parents ask before subscribing.
                </p>
                <div className="faq-list">
                    {FAQS.map((f) => (
                        <details className="faq-item" key={f.q}>
                            <summary>{f.q}</summary>
                            <div className="faq-body">{f.a}</div>
                        </details>
                    ))}
                </div>
            </div>
        </section>
    );
}
