const FAQS = [
    {
        q: "Is this really free?",
        a: "Yes. Every tutorial is free on YouTube and every practice PDF is free to download. No paywall, no email gate, no upsell.",
    },
    {
        q: "How is this different from Khan Academy SAT prep?",
        a: "This channel is built for the Digital SAT (post-March 2024) and ships two long-form tutorials a week, plus a YouTube Short most days. Each lesson teaches 3 named rules first, then walks 8 examples easy-to-hard — and every wrong answer is explained, not just the right one.",
    },
    {
        q: "What does ‘AI-validated explanations’ mean?",
        a: "Every per-choice explanation is generated by Claude Opus and re-checked by a separate logic critic. Anything ambiguous or wrong is flagged and regenerated. No voiceover or video is rendered until every explanation passes the gate.",
    },
    {
        q: "Do you cover Math too?",
        a: "Right now the channel focuses exclusively on Reading & Writing — all 10 SAT R&W question types are in active rotation. Math is on the roadmap.",
    },
    {
        q: "Are the practice tests scored like the real Digital SAT?",
        a: "Practice tests are 54 questions per module, matching the real Digital SAT module length. Difficulty is calibrated 30% easy / 40% medium / 30% hard, and a downloadable PDF ships with every tutorial.",
    },
];

export function FAQ() {
    return (
        <section className="section">
            <div className="container container-prose">
                <div className="section-eyebrow">FAQ</div>
                <h2>Frequently Asked Questions</h2>
                <p className="section-lede">
                    Everything students and parents ask before subscribing.
                </p>
                <div className="faq-list">
                    {FAQS.map((f) => (
                        <details className="faq-item" key={f.q}>
                            <summary>{f.q}</summary>
                            <div className="faq-body">{f.a}</div>
                        </details>
                    ))}
                </div>
            </div>
        </section>
    );
}
